$(call inherit-product, $(SRC_TARGET_DIR)/product/core_minimal.mk)

PRODUCT_DEVICE := kyf42
PRODUCT_NAME := omni_kyf42
PRODUCT_BRAND := KYOCERA
PRODUCT_MODEL := KYF42
PRODUCT_MANUFACTURER := kyocera
PRODUCT_RELEASE_NAME := KYOCERA KYF42

# Force TWRP compilation flags
PRODUCT_BOOTIMAGE_4K_ALIGNMENT := true